### ISSUE TITLE
M3: System architecture diagram rough draft

### ISSUE THREAD

**Issue by elanawood** [elanawood/Fossa-Force#33]

**Comment by elanawood** [comment]
# The team is going to make an architecture diagram for M3 anyways to help us form a cohesive understanding of the components of our system.

## Even though the M3 requirements changed we still feel that an architecture diagram would be valuable

**Comment by ahoffbauer127** [comment]
### research on software stack for entire project

- relevant to the architecture and sequence diagrams

**Comment by elanawood** [comment]
# https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

## flask resource
