### ISSUE TITLE
M3: Set up automated testing on Git

### ISSUE THREAD

**Issue by elanawood** [elanawood/Fossa-Force#36]

**Comment by elanawood** [comment]
# Will be in the test plan

**Comment by 1alimeg** [comment]
2 pull requests associated with this issue, each in different branches, each implementing different types of automated tests
Helpful resources: 
- https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/
- https://docs.github.com/en/actions/using-workflows/about-workflows
- https://docs.github.com/en/enterprise-server@3.10/actions/automating-builds-and-tests/building-and-testing-python
